# Generated by Django 2.0.9 on 2018-10-03 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('razao_social', models.CharField(max_length=50)),
                ('identificacao', models.CharField(max_length=50)),
                ('classificacao', models.CharField(max_length=18)),
                ('tipo_pessoa', models.CharField(max_length=10)),
                ('cnpj_cpf', models.CharField(max_length=15)),
                ('inscricao_estadual', models.CharField(max_length=20)),
                ('inscricao_municipal', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=50)),
                ('municipio', models.CharField(max_length=50)),
                ('cep', models.CharField(max_length=10)),
                ('uf', models.CharField(max_length=2)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('nome_titular', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=15)),
                ('funcao', models.CharField(max_length=50)),
            ],
        ),
    ]
